services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
    restart: unless-stopped  # ← FIX: hyphen, not underscore

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend
    restart: unless-stopped  # ← FIX: hyphen, not underscore

# Remove the version line at the top if present