services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama:11434
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama  # ← Simple dependency without health condition
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend  # ← This can stay simple too
    restart: unless-stopped

volumes:
  ollama_data: